console.log(process.execPath);
console.log(process.cwd());
console.log(process.env);
console.log(process.version);
console.log(process.versions);
console.log(process.arch);
console.log(process.platform);
console.log(process.memoryUsage());
console.log(process.uptime());
